version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: openMRP
      POSTGRES_PASSWORD: password
      POSTGRES_DB: openMRP
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - openMRP-network

  backend:
    build: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://openMRP:password@db/openMRP
    networks:
      - openMRP-network

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - openMRP-network

networks:
  openMRP-network:

volumes:
  postgres_data:
